<?php

namespace dsw\QuizBundle\Repository;

/**
 * AttemptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttemptRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findByQuestionnaire($id_questionnaire) {
                
        $qb = $this->_em->createQueryBuilder()
            ->select('att')
            ->from('dswQuizBundle:Attempt', 'att')
            
            // Jointure, fonctionne car les entités sont mappées
            ->leftJoin('att.answer', 'ans')
            ->leftJoin('ans.question', 'qion')
            ->leftJoin('qion.questionnaire', 'qre')
            
            // filtre
            ->where('qre.id = :id_questionnaire')
            ->setParameter(':id_questionnaire', $id_questionnaire)
            
            // ->addSelect('SUM(ans.score) AS score')
            // ->groupBy('att.user')
                        
            // trie
            //->orderBy('att.user', 'ASC')
        ;
        
        return $qb->getQuery()->getResult();
        
    }
    
    
    
    public function AttemptsByQuestionnaireAndUser($id_questionnaire, $id_user) {
                
        $qb = $this->_em->createQueryBuilder()
            ->select('att')
            ->from('dswQuizBundle:Attempt', 'att')
            
            // Jointure, fonctionne car les entités sont mappées
            ->leftJoin('att.answer', 'ans')
            ->leftJoin('ans.question', 'qion')
            ->leftJoin('qion.questionnaire', 'qre')
            
            // filtre
            ->where('qre.id = :id_questionnaire')
            ->setParameter(':id_questionnaire', $id_questionnaire)
            
            ->andWhere('att.user = :id_user')
            ->setParameter(':id_user', $id_user)
            
            // ->addSelect('SUM(ans.score) AS score')
            // ->groupBy('att.user')
                        
            // trie
            //->orderBy('att.user', 'ASC')
        ;
        
        return $qb->getQuery()->getResult();
        
    }
    
    
    
    public function findUsers($id_questionnaire) {
                
        $qb = $this->_em->createQueryBuilder()
            ->select('att')
            ->from('dswQuizBundle:Attempt', 'att')
            
            // Jointure, fonctionne car les entités sont mappées
            ->leftJoin('att.answer', 'ans')
            ->leftJoin('ans.question', 'qion')
            ->leftJoin('qion.questionnaire', 'qre')
            
            // filtre
            ->where('qre.id = :id_questionnaire')
            ->setParameter(':id_questionnaire', $id_questionnaire)
            
            // ->addSelect('SUM(ans.score) AS score')
            ->groupBy('att.user')
                        
            // trie
            //->orderBy('att.user', 'ASC')
        ;
        
        return $qb->getQuery()->getResult();
        
    }
    
}
