<?php

namespace Proxies\__CG__\dsw\LearnBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Course extends \dsw\LearnBundle\Entity\Course implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'id', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'name', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'description', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'code', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'modules', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'logo', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'open', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'public', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'learners'];
        }

        return ['__isInitialized__', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'id', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'name', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'description', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'code', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'modules', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'logo', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'open', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'public', '' . "\0" . 'dsw\\LearnBundle\\Entity\\Course' . "\0" . 'learners'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Course $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addModule(\dsw\LearnBundle\Entity\Module $module)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addModule', [$module]);

        return parent::addModule($module);
    }

    /**
     * {@inheritDoc}
     */
    public function removeModule(\dsw\LearnBundle\Entity\Module $module)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeModule', [$module]);

        return parent::removeModule($module);
    }

    /**
     * {@inheritDoc}
     */
    public function getModules()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModules', []);

        return parent::getModules();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublic($public = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublic', [$public]);

        return parent::setPublic($public);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublic', []);

        return parent::getPublic();
    }

    /**
     * {@inheritDoc}
     */
    public function addLearner(\dsw\UserBundle\Entity\User $learner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLearner', [$learner]);

        return parent::addLearner($learner);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLearner(\dsw\UserBundle\Entity\User $learner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLearner', [$learner]);

        return parent::removeLearner($learner);
    }

    /**
     * {@inheritDoc}
     */
    public function getLearners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLearners', []);

        return parent::getLearners();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpen($open = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpen', [$open]);

        return parent::setOpen($open);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpen', []);

        return parent::getOpen();
    }

}
