<?php

namespace Proxies\__CG__\dsw\AmpliBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Idee extends \dsw\AmpliBundle\Entity\Idee implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'id', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'titre', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'description', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'objectifs', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'methode', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'calendrier', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'video', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'imgProjet', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'imgEquipe', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'espace', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'user', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'coeurs', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'selection', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'categorie', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'equipe', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'commentaires', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'participations', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'imgProjetFile', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'imgEquipeFile'];
        }

        return ['__isInitialized__', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'id', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'titre', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'description', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'objectifs', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'methode', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'calendrier', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'video', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'imgProjet', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'imgEquipe', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'espace', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'user', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'coeurs', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'selection', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'categorie', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'equipe', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'commentaires', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'participations', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'imgProjetFile', '' . "\0" . 'dsw\\AmpliBundle\\Entity\\Idee' . "\0" . 'imgEquipeFile'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Idee $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjectifs($objectifs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjectifs', [$objectifs]);

        return parent::setObjectifs($objectifs);
    }

    /**
     * {@inheritDoc}
     */
    public function getObjectifs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjectifs', []);

        return parent::getObjectifs();
    }

    /**
     * {@inheritDoc}
     */
    public function setMethode($methode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMethode', [$methode]);

        return parent::setMethode($methode);
    }

    /**
     * {@inheritDoc}
     */
    public function getMethode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMethode', []);

        return parent::getMethode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalendrier($calendrier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalendrier', [$calendrier]);

        return parent::setCalendrier($calendrier);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalendrier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalendrier', []);

        return parent::getCalendrier();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspace(\dsw\AmpliBundle\Entity\Espace $espace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspace', [$espace]);

        return parent::setEspace($espace);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspace', []);

        return parent::getEspace();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\dsw\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function addCoeur(\dsw\AmpliBundle\Entity\Coeur $coeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCoeur', [$coeur]);

        return parent::addCoeur($coeur);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCoeur(\dsw\AmpliBundle\Entity\Coeur $coeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCoeur', [$coeur]);

        return parent::removeCoeur($coeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoeurs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoeurs', []);

        return parent::getCoeurs();
    }

    /**
     * {@inheritDoc}
     */
    public function setVideo($video)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVideo', [$video]);

        return parent::setVideo($video);
    }

    /**
     * {@inheritDoc}
     */
    public function getVideo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVideo', []);

        return parent::getVideo();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgProjet($imgProjet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgProjet', [$imgProjet]);

        return parent::setImgProjet($imgProjet);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgProjet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgProjet', []);

        return parent::getImgProjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgEquipe($imgEquipe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgEquipe', [$imgEquipe]);

        return parent::setImgEquipe($imgEquipe);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgEquipe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgEquipe', []);

        return parent::getImgEquipe();
    }

    /**
     * {@inheritDoc}
     */
    public function setSelection($selection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSelection', [$selection]);

        return parent::setSelection($selection);
    }

    /**
     * {@inheritDoc}
     */
    public function getSelection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSelection', []);

        return parent::getSelection();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(\dsw\AmpliBundle\Entity\Categorie $categorie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipe($equipe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipe', [$equipe]);

        return parent::setEquipe($equipe);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipe', []);

        return parent::getEquipe();
    }

    /**
     * {@inheritDoc}
     */
    public function addParticipation(\dsw\AmpliBundle\Entity\Participation $participation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParticipation', [$participation]);

        return parent::addParticipation($participation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParticipation(\dsw\AmpliBundle\Entity\Participation $participation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParticipation', [$participation]);

        return parent::removeParticipation($participation);
    }

    /**
     * {@inheritDoc}
     */
    public function getParticipations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParticipations', []);

        return parent::getParticipations();
    }

    /**
     * {@inheritDoc}
     */
    public function getImgProjetFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgProjetFile', []);

        return parent::getImgProjetFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgProjetFile(\Symfony\Component\HttpFoundation\File\UploadedFile $imgProjetFile = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgProjetFile', [$imgProjetFile]);

        return parent::setImgProjetFile($imgProjetFile);
    }

    /**
     * {@inheritDoc}
     */
    public function getImgEquipeFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImgEquipeFile', []);

        return parent::getImgEquipeFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setImgEquipeFile(\Symfony\Component\HttpFoundation\File\UploadedFile $imgEquipeFile = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImgEquipeFile', [$imgEquipeFile]);

        return parent::setImgEquipeFile($imgEquipeFile);
    }

    /**
     * {@inheritDoc}
     */
    public function uploadImgProjetFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'uploadImgProjetFile', []);

        return parent::uploadImgProjetFile();
    }

    /**
     * {@inheritDoc}
     */
    public function uploadImgEquipeFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'uploadImgEquipeFile', []);

        return parent::uploadImgEquipeFile();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadDir', []);

        return parent::getUploadDir();
    }

    /**
     * {@inheritDoc}
     */
    public function redim($src, $new_width, $prefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'redim', [$src, $new_width, $prefix]);

        return parent::redim($src, $new_width, $prefix);
    }

    /**
     * {@inheritDoc}
     */
    public function addCommentaire(\dsw\AmpliBundle\Entity\Commentaire $commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommentaire', [$commentaire]);

        return parent::addCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommentaire(\dsw\AmpliBundle\Entity\Commentaire $commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommentaire', [$commentaire]);

        return parent::removeCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaires()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaires', []);

        return parent::getCommentaires();
    }

}
