eval_question_index:
    path:     /
    defaults: { _controller: "dswEvalBundle:Question:index" }
    methods:  GET

eval_question_show:
    path:     /{id}/show
    defaults: { _controller: "dswEvalBundle:Question:show" }
    methods:  GET

eval_question_new:
    path:     /new
    defaults: { _controller: "dswEvalBundle:Question:new" }
    methods:  [GET, POST]

eval_question_edit:
    path:     /{id}/edit
    defaults: { _controller: "dswEvalBundle:Question:edit" }
    methods:  [GET, POST]

eval_question_delete:
    path:     /{id}/delete
    defaults: { _controller: "dswEvalBundle:Question:delete" }
    methods:  DELETE
