<?php

namespace dsw\EvalBundle\Repository;

/**
 * EvalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findEvaluationByEvaluateur($user_id)
      {
        
        //$qb = $this->createQueryBuilder('i');
        $qb = $this->_em->createQueryBuilder();

        $qb
            ->select('e')
            ->from('dswEvalBundle:Evaluation', 'e')
            
            ->leftJoin('e.evaluateurs', 'u')

            ->where('u.id = :id')
            ->setParameter('id', $user_id)
            
            
        ;
        
        // return $qb->getQuery()->getResult();
        return $qb->getQuery()->getOneOrNullResult();
        
      }
    
    
}
