<?php

namespace dsw\LearnBundle\Repository;

/**
 * UnitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function countUnits($id_module) {
        
        $qb = $this->_em->createQueryBuilder();

        $qb
            
            ->from('dswLearnBundle:Unit', 'u')
            ->select('count(u.id)')
            ->where('u.module = :id')
            ->setParameter('id', $id_module)
            
        ;
        
        return $qb->getQuery()->getSingleScalarResult();
        
    }
    
}
